In [1]:
import tensorflow as tf

c:\Users\aayus\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


## Exercise 1: Implementing a Mathematical Equation

In [2]:
X=3
Y=4

In [3]:
X = tf.Variable(3)
Y = tf.Variable(4)
C =tf.constant(2)

In [4]:
def myfunc(x,y,c):
    Z = x*x*y+y+c
    return Z

In [5]:
result = myfunc(X,Y,C)
tf.print(result)

42


## Exercise 2: Matrix Multiplication Using TensorFlow

In [6]:
X=tf.Variable([[1,2,3],[4,5,6]])
Y=tf.Variable([[7,8],[9,10],[11,12]])

In [7]:
tf.print(X)

[[1 2 3]
 [4 5 6]]


In [8]:
tf.print(Y)

[[7 8]
 [9 10]
 [11 12]]


In [9]:
c1=tf.matmul(X,Y)
tf.print(c1)

[[58 64]
 [139 154]]


In [10]:
c2=tf.matmul(Y,X)
tf.print(c2)

[[39 54 69]
 [49 68 87]
 [59 82 105]]


## Exercise 3: Reshaping Matrices Using the reshape() Function in TensorFlow

In [11]:
A=tf.Variable([[1,2,3,4], \
[5,6,7,8], \
[9,10,11,12], \
[13,14,15,16], \
[17,18,19,20]])

tf.print(A)

[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [12]:
A.shape

TensorShape([5, 4])

In [13]:
tf.print(tf.reshape(A,[5,4,1]))

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


In [14]:
A.shape

TensorShape([5, 4])

In [15]:
A = tf.reshape(A,[5,4,1])
A.shape

TensorShape([5, 4, 1])

In [16]:
tf.print(A)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


## Exercise 4: Implementing the argmax() Function

In [17]:
X=tf.Variable([[91,12,15], [11,88,21],[90, 87,75]])
tf.print(X)

[[91 12 15]
 [11 88 21]
 [90 87 75]]


In [18]:
X.shape

TensorShape([3, 3])

In [19]:
tf.print(tf.argmax(X,axis=0))

[0 1 2]


In [20]:
tf.print(tf.argmax(X,axis=1))

[0 1 0]


## Exercise 5: Using an Optimizer for a Simple Linear Regression

In [21]:
w=tf.Variable(0.0)
b=tf.Variable(0.0)

In [22]:
def regression(x):
    model=w*x+b
    return model

In [23]:
x=[1,2,3,4]
y=[0,-1,-2,-3]

In [24]:
loss=lambda:abs(regression(x)-y)

In [25]:
optimizer=tf.optimizers.Adam(.01)

In [26]:
for i in range(1000):
    optimizer.minimize(loss,[w,b])

In [27]:
tf.print(w,b)

-1.00371706 0.999803364


In [28]:
tf.print(regression([1,2,3,4]))

[-0.00391370058 -1.00763083 -2.01134801 -3.01506495]


## Exercise 6: Creating an ANN with TensorFlow

In [32]:
model = tf.keras.Sequential()

In [33]:
model.add(tf.keras.layers.InputLayer(input_shape=(8,),name='Input_layer'))

In [34]:
model.add(tf.keras.layers.Dense(4, activation='relu',name='First_hidden_layer'))
model.add(tf.keras.layers.Dense(1,name='Output_layer'))

In [35]:
model.variables

[<tf.Variable 'First_hidden_layer/kernel:0' shape=(8, 4) dtype=float32, numpy=
 array([[ 0.55009085,  0.2919436 ,  0.5748295 , -0.34787402],
        [-0.09321672, -0.37711447,  0.46967953, -0.67726123],
        [ 0.5402648 ,  0.6971249 , -0.11240005, -0.66107804],
        [-0.49862146,  0.2718708 , -0.26361892, -0.36784843],
        [-0.04677522, -0.28189176,  0.43769854,  0.12011516],
        [-0.01570392, -0.4826561 ,  0.59585696,  0.2848729 ],
        [ 0.09810555, -0.6700988 ,  0.30876034, -0.63297147],
        [-0.01179856, -0.3511237 , -0.12783188, -0.5855758 ]],
       dtype=float32)>,
 <tf.Variable 'First_hidden_layer/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'Output_layer/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[-0.24457657],
        [ 1.0786743 ],
        [-0.91161597],
        [ 0.25506794]], dtype=float32)>,
 <tf.Variable 'Output_layer/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [36]:
data = tf.random.normal((32,8))

In [40]:
prediction = model.predict(data)
prediction


1/1 [==============================] - 0s 29ms/step


array([[ 0.17184049],
       [ 0.79238284],
       [ 1.9228483 ],
       [-1.2778416 ],
       [ 1.1470045 ],
       [-0.79602414],
       [-2.3452237 ],
       [ 0.12282   ],
       [ 0.03623555],
       [ 0.3289487 ],
       [ 0.59997034],
       [ 0.92210627],
       [-1.6438384 ],
       [-1.6519547 ],
       [-1.0238655 ],
       [ 1.4052039 ],
       [ 0.67340666],
       [ 3.113067  ],
       [ 1.8922404 ],
       [-3.618649  ],
       [ 0.9346123 ],
       [ 0.55231494],
       [ 1.074933  ],
       [-1.9399177 ],
       [-1.2240968 ],
       [ 2.189323  ],
       [-1.370307  ],
       [-0.37555504],
       [-1.25015   ],
       [ 0.32761988],
       [-1.257606  ],
       [ 1.9377168 ]], dtype=float32)

## Exercise 7: Creating a Linear Regression Model as an ANN with TensorFlow

In [42]:
import pandas as pd
df = pd.read_csv("Bias_correction_ucl.csv")

In [43]:
df.drop('Date', inplace=True, axis=1)
df.dropna(inplace=True)

In [44]:
target = df[['Next_Tmax', 'Next_Tmin']]
features = df.drop(['Next_Tmax', 'Next_Tmin'],
axis=1)

In [45]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
feature_array = scaler.fit_transform(features)
features = pd.DataFrame(feature_array,columns=features.columns)

In [46]:
model = tf.keras.Sequential()

In [47]:
model.add(tf.keras.layers.InputLayer(input_shape=(features.shape[1],), name='Input_layer'))

In [48]:
model.add(tf.keras.layers.Dense(2,name='Output_layer'))

In [49]:
model.compile(tf.optimizers.RMSprop(0.001),loss='mse')

In [50]:
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir="./logs")

In [51]:
model.fit(x=features.to_numpy(),
y=target.to_numpy(),\
epochs=50,
callbacks=[tensorboard_callback])

Epoch 1/50
238/238 [==============================] - 2s 3ms/step - loss: 669.7455
Epoch 2/50
238/238 [==============================] - 1s 3ms/step - loss: 564.4802
Epoch 3/50
238/238 [==============================] - 1s 3ms/step - loss: 468.9808
Epoch 4/50
238/238 [==============================] - 1s 3ms/step - loss: 382.8988
Epoch 5/50
238/238 [==============================] - 1s 2ms/step - loss: 306.5018
Epoch 6/50
238/238 [==============================] - 1s 3ms/step - loss: 239.7127
Epoch 7/50
238/238 [==============================] - 1s 2ms/step - loss: 182.5094
Epoch 8/50
238/238 [==============================] - 1s 3ms/step - loss: 134.7769
Epoch 9/50
238/238 [==============================] - 1s 3ms/step - loss: 96.6941
Epoch 10/50
238/238 [==============================] - 1s 4ms/step - loss: 68.1397
Epoch 11/50
238/238 [==============================] - 1s 5ms/step - loss: 48.4379
Epoch 12/50
238/238 [==============================] - 1s 3ms/step - loss: 35.4436
Epoch

In [52]:
loss = model.evaluate(features.to_numpy(),
target.to_numpy())
print('loss:', loss)

238/238 [==============================] - 0s 1ms/step - loss: 3.5949
loss: 3.5948596000671387


## Exercise 8: Creating a Multi-Layer ANN with TensorFlow

In [54]:
df = pd.read_csv('Bias_correction_ucl.csv')

In [56]:
df.drop('Date', inplace=True, axis=1)
df.dropna(inplace=True)

In [59]:
target = df[['Next_Tmax', 'Next_Tmin']]
features = df.drop(['Next_Tmax', 'Next_Tmin'],axis=1)

In [60]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
feature_array = scaler.fit_transform(features)
features = pd.DataFrame(feature_array,
columns=features.columns)

In [61]:
model = tf.keras.Sequential()

In [62]:
model.add(tf.keras.layers.InputLayer(input_shape=(features.shape[1],), name='Input_layer'))

In [63]:
model.add(tf.keras.layers.Dense(16,
name='Dense_layer_1'))
model.add(tf.keras.layers.Dense(8,
name='Dense_layer_2'))
model.add(tf.keras.layers.Dense(4,
name='Dense_layer_3'))
model.add(tf.keras.layers.Dense(2,
name='Output_layer'))

In [64]:
model.compile(tf.optimizers.RMSprop(0.001),
loss='mse')

In [65]:
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir="./logs")

In [66]:
model.fit(x=features.to_numpy(),
y=target.to_numpy(),epochs=50, callbacks=[tensorboard_callback],validation_split=0.2)

Epoch 1/50
190/190 [==============================] - 1s 3ms/step - loss: 227.5352 - val_loss: 21.0922
Epoch 2/50
190/190 [==============================] - 0s 1ms/step - loss: 10.7658 - val_loss: 6.0179
Epoch 3/50
190/190 [==============================] - 0s 2ms/step - loss: 4.8107 - val_loss: 4.8855
Epoch 4/50
190/190 [==============================] - 1s 4ms/step - loss: 3.8400 - val_loss: 4.4099
Epoch 5/50
190/190 [==============================] - 1s 4ms/step - loss: 3.2993 - val_loss: 3.7028
Epoch 6/50
190/190 [==============================] - 1s 7ms/step - loss: 2.9177 - val_loss: 3.2037
Epoch 7/50
190/190 [==============================] - 1s 6ms/step - loss: 2.6343 - val_loss: 3.3077
Epoch 8/50
190/190 [==============================] - 1s 3ms/step - loss: 2.4184 - val_loss: 2.7477
Epoch 9/50
190/190 [==============================] - 1s 4ms/step - loss: 2.2631 - val_loss: 2.4710
Epoch 10/50
190/190 [==============================] - 1s 4ms/step - loss: 2.1538 - val_loss: 2.

In [67]:
loss = model.evaluate(features.to_numpy(),
target.to_numpy())
print('loss:', loss)

238/238 [==============================] - 1s 2ms/step - loss: 1.6226
loss: 1.6226309537887573


## Exercise 9: Creating a Logistic Regression Model as an ANN with TensorFlow

In [69]:
df = pd.read_csv('qsar_androgen_receptor.csv',sep=';')

In [70]:
df.dropna(inplace=True)

In [71]:
target = df['positive'].apply(lambda x: 1 if x=='positive' else 0)
features = df.drop('positive', axis=1)

In [72]:
model = tf.keras.Sequential()

In [73]:
model.add(tf.keras.layers.InputLayer(input_shape=(features.shape[1],), name='Input_layer'))

In [74]:
model.add(tf.keras.layers.Dense(1,name='Output_layer', activation='sigmoid'))

In [75]:
model.compile(tf.optimizers.RMSprop(0.0001), \
loss='binary_crossentropy',
metrics=['accuracy'])

In [77]:
tensorboard_callback =tf.keras.callbacks.TensorBoard\
(log_dir="./logs")

In [78]:
model.fit(x=features.to_numpy(), y=target.to_numpy(),epochs=50, callbacks=[tensorboard_callback]
, validation_split=0.2)

Epoch 1/50
43/43 [==============================] - 1s 8ms/step - loss: 0.6383 - accuracy: 0.6773 - val_loss: 0.5147 - val_accuracy: 0.8609
Epoch 2/50
43/43 [==============================] - 0s 3ms/step - loss: 0.5898 - accuracy: 0.7730 - val_loss: 0.4504 - val_accuracy: 0.8994
Epoch 3/50
43/43 [==============================] - 0s 3ms/step - loss: 0.5551 - accuracy: 0.8182 - val_loss: 0.4078 - val_accuracy: 0.9201
Epoch 4/50
43/43 [==============================] - 0s 2ms/step - loss: 0.5295 - accuracy: 0.8472 - val_loss: 0.3820 - val_accuracy: 0.9260
Epoch 5/50
43/43 [==============================] - 0s 2ms/step - loss: 0.5113 - accuracy: 0.8553 - val_loss: 0.3645 - val_accuracy: 0.9260
Epoch 6/50
43/43 [==============================] - 0s 2ms/step - loss: 0.4965 - accuracy: 0.8605 - val_loss: 0.3473 - val_accuracy: 0.9260
Epoch 7/50
43/43 [==============================] - 0s 2ms/step - loss: 0.4830 - accuracy: 0.8650 - val_loss: 0.3350 - val_accuracy: 0.9260
Epoch 8/50
43/43 [==

In [79]:
loss, accuracy = model.evaluate(features.to_numpy(),
\
target.to_numpy())
print(f'loss: {loss}, accuracy: {accuracy}')

53/53 [==============================] - 0s 838us/step - loss: 0.2792 - accuracy: 0.9081
loss: 0.27915987372398376, accuracy: 0.90806645154953
